name: Nix CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - 'master'
          - 'v8.14'
      fail-fast: false
    steps:
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: coq
      - uses: cachix/cachix-action@v8
        with:
          name: coq-community
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - uses: cachix/cachix-action@v8
        with:
          name: math-comp
      - uses: actions/checkout@v2
      - run: >
          nix-build https://coq.inria.fr/nix/toolbox --argstr job pocklington --arg override '{coq = "'${{ matrix.coq_version }}'"; pocklington = builtins.filterSource (path: _: baseNameOf path != ".git") ./.;}'
